// Generates packages/contracts/src/generated/wire.ts from
// ../schema/logical-schema.snapshot.json (the backend snapshot extracted from
// X44421/stillflow). Deterministic: same snapshot in, byte-identical TS out.
//
// This script is the only sanctioned writer of src/generated/. Hand edits are
// rejected by scripts/verify.mjs (regenerate + byte compare).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(here, "..");
const snapshotPath = join(packageRoot, "schema", "logical-schema.snapshot.json");
const outputPath = join(packageRoot, "src", "generated", "wire.ts");

const snapshot = JSON.parse(readFileSync(snapshotPath, "utf8"));

/** Renders a payload type reference from the snapshot IR. */
function renderPayload(payload) {
  if (payload === null) return null;
  switch (payload.type) {
    case "object": {
      const fields = payload.fields
        .map((field) => {
          const optional = field.optional ? "?" : "";
          const nullable = field.nullable ? " | null" : "";
          return `readonly ${field.name}${optional}: ${field.type}${nullable}`;
        })
        .join("; ");
      return `{ ${fields} }`;
    }
    case "array":
      return `readonly ${payload.items}[]`;
    default:
      return payload.type;
  }
}

function renderFieldType(field) {
  if (field.type === "array" && field.items) return `readonly ${field.items}[]`;
  if (field.type === "object" && field.fields) return renderPayload(field);
  return field.type;
}

function renderField(field) {
  const optional = field.optional ? "?" : "";
  const nullable = field.nullable ? " | null" : "";
  const note = field.note ? ` // ${field.note}` : "";
  return `  readonly ${field.name}${optional}: ${renderFieldType(field)}${nullable};${note}`;
}

function renderTaggedEnum(type) {
  const members = type.variants.map((variant) => {
    const payload = renderPayload(variant.payload);
    const note = variant.note ? ` // ${variant.note}` : "";
    return payload === null
      ? `  | { readonly kind: "${variant.name}" }${note}`
      : `  | { readonly kind: "${variant.name}"; readonly value: ${payload} }${note}`;
  });
  return `export type ${type.name} =\n${members.join("\n")};\n`;
}

function renderUnitEnum(type) {
  const members = type.variants.map((v) => `"${v}"`).join(" | ");
  return `export type ${type.name} = ${members};\n`;
}

function renderStruct(type) {
  const fields = type.fields.map(renderField).join("\n");
  return `export interface ${type.name} {\n${fields}\n}\n`;
}

function renderAlias(type) {
  return `export type ${type.name} = ${type.target};\n`;
}

function renderConstant(constant) {
  const value =
    typeof constant.value === "number" || typeof constant.value === "boolean"
      ? constant.value
      : JSON.stringify(constant.value);
  return `export const ${constant.name} = ${value};`;
}

const lines = [];
lines.push("// GENERATED FILE — DO NOT EDIT.");
lines.push("//");
lines.push(`// Generated by scripts/generate.mjs from schema/${"logical-schema.snapshot.json"}.`);
lines.push(`// Snapshot source: ${snapshot.source.repository}@${snapshot.source.ref}`);
lines.push(`// Extracted at: ${snapshot.source.extractedAt} (${snapshot.source.method})`);
lines.push("//");
lines.push("// Regenerate with: bun run --cwd packages/contracts generate");
lines.push("");
lines.push("// ---------------------------------------------------------------------------");
lines.push("// Version and bound constants — the single source of truth on the client side.");
lines.push("// Literal version constants elsewhere in TS are forbidden (FE0-C1 §3).");
lines.push("// ---------------------------------------------------------------------------");
lines.push("");
for (const constant of snapshot.constants) {
  lines.push(`/** ${constant.rust} */`);
  lines.push(renderConstant(constant));
  lines.push("");
}
lines.push("// ---------------------------------------------------------------------------");
lines.push("// Wire types");
lines.push("// ---------------------------------------------------------------------------");
lines.push("");
for (const type of snapshot.types) {
  if (type.note) lines.push(`/** ${type.note} */`);
  switch (type.kind) {
    case "alias":
      lines.push(renderAlias(type));
      break;
    case "unitEnum":
      lines.push(renderUnitEnum(type));
      break;
    case "taggedEnum":
      lines.push(renderTaggedEnum(type));
      break;
    case "struct":
      lines.push(renderStruct(type));
      break;
    default:
      throw new Error(`unknown snapshot type kind: ${type.kind}`);
  }
}

const output = lines.join("\n");

if (process.argv.includes("--stdout")) {
  // Used by scripts/verify.mjs for byte-comparison drift checks.
  process.stdout.write(output);
} else {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, output, "utf8");
  process.stdout.write(`generated ${outputPath} from snapshot v${snapshot.snapshotVersion}\n`);
}
