// Drift check: regenerates src/generated/wire.ts in memory from the committed
// snapshot and byte-compares against the committed output. Any hand edit to
// generated code, or any snapshot refresh without regeneration, exits 1.
// Designed for CI (FE1-S6 wires this as the contracts drift gate).
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(here, "..");
const outputPath = join(packageRoot, "src", "generated", "wire.ts");
const snapshotPath = join(packageRoot, "schema", "logical-schema.snapshot.json");

const snapshot = JSON.parse(readFileSync(snapshotPath, "utf8"));
const committed = readFileSync(outputPath, "utf8");

const { execFileSync } = await import("node:child_process");
const regenerated = execFileSync(
  process.execPath,
  [join(here, "generate.mjs"), "--stdout"],
  { cwd: packageRoot, encoding: "utf8" },
);

if (committed === regenerated) {
  process.stdout.write(
    `contracts drift check: OK (snapshot v${snapshot.snapshotVersion} matches generated output)\n`,
  );
} else {
  const firstDiff = [...committed].findIndex((ch, i) => ch !== regenerated[i]);
  process.stderr.write(
    [
      "contracts drift check: FAILED",
      `  committed bytes: ${Buffer.byteLength(committed)}`,
      `  regenerated bytes: ${Buffer.byteLength(regenerated)}`,
      `  first differing offset: ${firstDiff}`,
      "",
      "Fix: bun run --cwd packages/contracts generate   (then commit the regenerated file)",
    ].join("\n"),
  );
  process.exit(1);
}
